name: Actualizar Rio Genil

on:
  schedule:
    - cron: '7,22,37,52 * * * *'
  repository_dispatch:
    types: [scrape]
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Guardar cambios
        run: |
          git config --global user.name 'RioBot'
          git config --global user.email 'bot@noreply.github.com'
          git add datos.json historico.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizacion automatica niveles" && git push)