name: Actualizar Rio Genil

on:
  schedule:
    - cron: '*/15 * * * *'  # Se ejecuta cada 15 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Permiso necesario para guardar el archivo JSON
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar peticiones (requests)
        run: pip install requests

      - name: Ejecutar Robot Scraper
        run: python scraper.py

      - name: Guardar cambios (Commit & Push)
        run: |
          git config --global user.name 'RioBot'
          git config --global user.email 'bot@noreply.github.com'
          # Solo hacemos commit si datos.json ha cambiado
          git add datos.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizacion automatica niveles" && git push)
